repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python

        
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        language_version: python
    
  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: ["--max-line-length=100"]
        exclude: 'migrations/'

  - repo: git@github.com:pre-commit/mirrors-isort.git
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: 'migrations/'
