# Generated by Django 5.2 on 2025-04-26 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=250)),
                ("alert_uuid", models.UUIDField(unique=True)),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("Theft", "Theft"),
                            ("Suspicious", "Suspicious"),
                            ("Normal", "Normal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("time_spotted", models.DateTimeField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.company"
                    ),
                ),
            ],
        ),
    ]
